version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Zipping lambda..."
      - zip -r function.zip index.js

artifacts:
  files:
    - function.zip


    